# 工作流程名称
name: "Node.js CI with Multi-arch Docker Image"

# 手动触发工作流
on:
  workflow_dispatch:

# 作业
jobs:
  docker:
    name: Building and Pushing Node.js Multi-arch Docker Image
    runs-on: ubuntu-latest
    steps:
      # 检出代码库
      - uses: actions/checkout@v3

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 设置 QEMU 以支持多架构构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # 构建并推送镜像
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloud-clipboard:latest
